# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute perimeters for many subsets in C++
#' @param subsets list of integer vectors of polygon-IDs
#' @param keyPolygonIds list of integer vectors (per segment)
#' @param lengths numeric vector of segment lengths
#' @param Pmax integer maximum polygon ID
#' @return numeric vector of perimeters
#' @noRd
compute_perimeters <- function(subsets, keyPolygonIds, lengths, Pmax) {
    .Call(`_optimTFE_compute_perimeters`, subsets, keyPolygonIds, lengths, Pmax)
}

#' Generate Multiple Solutions as a Data Frame
#'
#' This function iterates over solution_ids, calls `solution_gen` for each ID,
#' and combines all results into a single data frame. The solution generation
#' process implements a greedy algorithm that iteratively selects planning units
#' with high species richness to satisfy species targets across subregions.
#'
#' @param solution_ids IntegerVector of solution IDs. One solution will be
#'   generated for each ID provided.
#' @param suitability NumericMatrix of species suitability scores, with planning
#'   units as rows and species as columns.
#' @param spp_targets IntegerVector of target populations for each species.
#' @param unit_regions IntegerVector mapping planning units to their respective
#'   regions.
#' @param unit_counts IntegerMatrix of unit counts by species and region.
#' @param regional_min IntegerMatrix of minimum targets for each species by region.
#' @param regional_max IntegerMatrix of maximum targets for each species by region.
#' @param populations IntegerMatrix specifying known populations for each
#'   species in each planning unit.
#' @param population_counts IntegerMatrix of population counts by species and region.
#' @param single_pu_pop Logical flag indicating whether only one unit should be
#'   selected per known population (default = TRUE).
#' @param rand_tolerance Integer specifying the range of species richness from
#'   maximum to consider for selection at each iteration (default = 5).
#' @param max_spp_selected Integer maximum number of species to select in each
#'   location to reduce 'species packing' within units. Use -1 for no limit.
#' @param spp_names CharacterVector of species names.
#' @param seed Unsigned 64-bit integer seed for random number generation.
#' @param incompat Optional IntegerMatrix specifying species incompatibilities,
#'   where 1 indicates two species cannot share the same planning unit.
#' @return A data frame with columns: solution, order, unit_id, passing, and
#'   one column per species indicating which species targets are satisfied
#'   in each planning unit.
#' @noRd
solutions_gen_df <- function(solution_ids, suitability, spp_targets, unit_regions, unit_counts, regional_min, regional_max, populations, population_counts, single_pu_pop, rand_tolerance, max_spp_selected, spp_names, seed, incompat = NULL) {
    .Call(`_optimTFE_solutions_gen_df`, solution_ids, suitability, spp_targets, unit_regions, unit_counts, regional_min, regional_max, populations, population_counts, single_pu_pop, rand_tolerance, max_spp_selected, spp_names, seed, incompat)
}

