# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_unit <- function(suitability_mx, targets, rand_tolerance) {
    .Call(`_optimTFE_select_unit`, suitability_mx, targets, rand_tolerance)
}

solution_gen <- function(suitability, targets, regions, regional_min, regional_max, populations, population_counts, single_pu_pop, rand_tolerance, max_spp_selected, solution_id = 1L) {
    .Call(`_optimTFE_solution_gen`, suitability, targets, regions, regional_min, regional_max, populations, population_counts, single_pu_pop, rand_tolerance, max_spp_selected, solution_id)
}

